account/urls.py
from django.urls import path

from . import views

app_name="account"

urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('profile/',views.profile,name='profile'),
    path('profile/edit',views.profile_edit,name='profile_edit'),
]

contact/urls.py
from django.urls import path 
from . import views

app_name='contact'
urlpatterns = [
    path('',views.contact_us,name='contact')
]

homepage/urls.py
from django.urls import path
from .import views



urlpatterns = [
    path('',views.home,name='home'),
]

job/urls.py
from django.urls import path
from . import views
from . import api
app_name='job'
urlpatterns = [
    path('',views.job_list,name='job_list'),
    path('add',views.add,name='add'),
    path('<str:slug>',views.job_detail,name='job_detail'),

    # function based view, api 
    path('api/jobs',api.job_list_api,name='job_list_api'),
    path('api/jobs/<int:id>',api.job_detail_api,name='job_detail_api'),


    # class , api
    path('api/jobs/add',api.AddJobListApi.as_view(),name='AddJobListApi'),
    path('api/jobs/edit/<int:id>',api.JobEditApi.as_view(),name='JobEditApi'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('homepage.urls') ),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('account.urls',namespace='accounts') ),
    path('admin/', admin.site.urls),
    path('jobs/',include('job.urls',namespace='jobs')),
    path('contact', include('contact.urls',namespace='contact')),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('homepage.urls') ),
    
    

]+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    city=models.ForeignKey('City',on_delete=models.CASCADE,null=True,blank=True)
    phone_number=models.CharField(max_length=15)
    image=models.ImageField(upload_to='profile/')
    
    def __str__(self):
        return str(self.user)
    


@receiver(post_save, sender=User) 
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)






class City(models.Model):
    name=models.CharField(max_length=50)

    def __str__(self):
        return self.name
    

contact/models.py
from django.db import models

# Create your models here.
class Info(models.Model):
    place=models.CharField(max_length=200)
    phone_number=models.CharField(max_length=15)
    email=models.EmailField(max_length=400)

    def __str__(self):
        return self.email
    

homepage/models.py
from django.db import models

# Create your models here.

job/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

# Create your models here.

JOB_TYPE=[
    ('part time','part time'),
    ('full time','full time'),
]



class Job(models.Model):
    user=models.ForeignKey( User ,on_delete=models.CASCADE)
    title=models.CharField(max_length=100)
    # location
    job_type=models.CharField(max_length=20,choices=JOB_TYPE)
    description=models.TextField(max_length=1000)
    Published_at=models.DateTimeField(auto_now=True)
    Vacancy=models.IntegerField(default=1)
    Salary=models.IntegerField(default=0)
    experience=models.IntegerField(default=1)
    category=models.ForeignKey('Category',on_delete=models.CASCADE)
    image=models.ImageField(upload_to='jobphoto/%y/%m/%d')
    slug=models.SlugField(null=True,blank=True)




    def save(self,*args,**kwargs):
        self.slug=slugify(self.title)
        super(Job,self).save(*args,**kwargs)

    def __str__(self):
        return self.title

class Category(models.Model):
    name=models.CharField(max_length=30)
    def __str__(self):
        return self.name
        
    

class Apply(models.Model):
    job=models.ForeignKey(Job,on_delete=models.CASCADE)
    name=models.CharField(max_length=50)
    email=models.EmailField(max_length=100)
    website=models.URLField(max_length=100)
    cv=models.FileField(upload_to='applyjob/')
    coverletter=models.TextField(max_length=500)
    created_at=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name
    
    

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile
class SignupForm(UserCreationForm):
    model=User
    fields='__all__'



class UserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['first_name','last_name','email']




class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=['city','phone_number','image']
    

account/views.py
from django.shortcuts import render , redirect ,reverse
from django.contrib.auth import authenticate,login
from .forms import SignupForm , UserForm ,ProfileForm
from .models import Profile
def signup(request):
    if request.method=='POST':
        form=SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data['username']
            password=form.cleaned_data['password1']
            user=authenticate(username=username,password=password)
            login(request,user)
            return redirect('/accounts/profile')

    else:
        form=SignupForm()
    return render(request,'registration/signup.html',{'form':form})




def profile(request):
    profile=Profile.objects.get(user=request.user)
    return render(request,'accounts/profile.html',{'profile':profile})





def profile_edit(request):
    profile=Profile.objects.get(user=request.user)
    if request.method=='POST':
        userform=UserForm(request.POST ,request.FILES,instance=request.user)
        profileform=ProfileForm(request.POST,request.FILES,instance=profile)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            myprofileform=profileform.save(commit=False)
            myprofileform.user = request.user
            myprofileform.save()
            return redirect('/accounts/profile')
   
    else:
        userform=UserForm(instance=request.user)
        profileform=ProfileForm(instance=Profile)
    return render(request,'accounts/profile_edit.html',{'userform':userform , 'profileform':profileform})

contact/views.py
from django.shortcuts import render
from .models import Info
from django.core.mail import send_mail
from django.conf import settings
# Create your views here.
def contact_us(request):
    info=Info.objects.first()
    if request.method=='POST':
        subject=request.POST['subject']
        email=request.POST['email']
        message=request.POST['message']


    # send email
        send_mail(
            subject,
            message,
            settings.EMAIL_HOST_USER,
            [email],
    
)


    return render(request,'contact/contact.html',{'info':info})

homepage/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'home/home.html')

job/views.py
from django.shortcuts import render
from .models import Job
from django.core.paginator import Paginator
from .form import ApplyForm
from .form import PostForm
from django.contrib.auth.decorators import login_required
from .filters import JobFilter
# Create your views here.
def job_list(request):
    job_list=Job.objects.all()
    # filter
    filter =JobFilter(request.GET, queryset=job_list)
    job_list=filter.qs

    paginator = Paginator(job_list, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context={'jobs':page_obj ,'filter':filter }
    return render(request,'job/job_list.html',context)

def job_detail(request , slug):
    job_detail=Job.objects.get(slug=slug)
    if request.method == 'POST':
        form=ApplyForm(request.POST , request.FILES)
        if form.is_valid:
            myform=form.save(commit=False)
            myform.job=job_detail
            myform.save()      
    else:
        form=ApplyForm()
    context={'job':job_detail,'form':form}
    return render(request,'job/job_detail.html',context)

@login_required
def add(request):
    if request.method=='POST':
        form=PostForm(request.POST , request.FILES)
        if form.is_valid:
            my_form=form.save(commit=False)
            my_form.user = request.user
            my_form.save()
           
    else:
         form=PostForm()

    return render(request,'add/add.html',{'form':form})

account/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap5form %}

{% block body %}



<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{job}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
    <div class="container">
  
            <div class="col-lg-8 mx-auto">
                <div class="job_sumary">
                    <div class="summery_header">
                        <h3>profile Summery</h3>
                    </div>
                    <div class="job_content">
                        <ul>
                            <li>name: <span>{{profile}}</span></li>
                            <li>email: <span>{{profile.user.email}}</span></li>
                            <li>city: <span>{{profile.city}}</span></li>
                            <li>phone: <span>{{profile.phone_number}}</span></li>
                            <li>image: <span> {{profile.image}}</span></li>
                            
                        </ul>
                    </div>
                    <a  class="boxed-btn3 w-100" href="{%url 'accounts:profile_edit'%}">Edit profile</a>
                </div>
  
   
                    <div class="job_lok_inner">
                        <div id="map" style="height: 200px;"></div>
                        <script>
                            function initMap() {
                                var uluru = { lat: -25.363, lng: 131.044 };
                                var grayStyles = [
                                    {
 
                          
                       
                       
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{%static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{%static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{%static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{%static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{%static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{%static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{%static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{%static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{%static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{%static 'css/slicknav.css' %}">

    <link rel="stylesheet" href="{%static 'css/style.css' %}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="index.html">
                                        <img src="img/logo.png" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li><a href="{%url 'home'%}">home</a></li>
                                            <li><a href="{%url 'jobs:job_list'%}">Browse Job</a></li>                                                                        
                                            <li><a href="{%url 'contact:contact'%}">Contact</a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                <div class="Appointment">                            
                            {% if request.user.is_authenticated  %}                                   
                                <div class="phone_num d-none d-xl-block">
                                    <a href="{%url 'accounts:profile'%}">profile</a>
                                </div>
                            {% else %} 
                                <div class="phone_num d-none d-xl-block">
                                    <a href="{%url 'login'%}">Log in</a>
                                </div>                                                                                
                            {% endif %}
    
                            {% if request.user.is_authenticated  %}                                   
                                <div class="phone_num d-none d-xl-block">
                                    
                                </div>
                            {% else %} 
                                <div class="phone_num d-none d-xl-block">
                                    <a href="{%url 'accounts:signup'%}">Sign Up</a>
                                 </div>                                                                                
                            {% endif %}        
                        
                            
                                    <div class="d-none d-lg-block">
                                        <a class="boxed-btn3" href="{%url 'jobs:add'%}">Post a Job</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                            
                            

                        </div>

                        

                    </div>

                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->

    

{% block body %}
{% endblock body %}
 <!-- footer start -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                            <div class="footer_logo">
                                <a href="#">
                                    <img src="img/logo.png" alt="">
                                </a>
                            </div>
                            <p>
                                finloan@support.com <br>
                                +10 873 672 6782 <br>
                                600/D, Green road, NewYork
                            </p>
                            <div class="socail_links">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="ti-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-google-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-instagram"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-2 col-md-6 col-lg-2">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                            <h3 class="footer_title">
                                Company
                            </h3>
                            <ul>
                                <li><a href="#">About </a></li>
                                <li><a href="#"> Pricing</a></li>
                                <li><a href="#">Carrier Tips</a></li>
                                <li><a href="#">FAQ</a></li>
                            </ul>

                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                            <h3 class="footer_title">
                                Category
                            </h3>
                            <ul>
                                <li><a href="#">Design & Art</a></li>
                                <li><a href="#">Engineering</a></li>
                                <li><a href="#">Sales & Marketing</a></li>
                                <li><a href="#">Finance</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-6 col-lg-4">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                            <h3 class="footer_title">
                                Subscribe
                            </h3>
                            <form action="#" class="newsletter_form">
                                <input type="text" placeholder="Enter your mail">
                                <button type="submit">Subscribe</button>
                            </form>
                            <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
                                luckily.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
            <div class="container">
                <div class="footer_border"></div>
                <div class="row">
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->
    <script src="{%static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <script src="{%static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{%static 'js/popper.min.js' %}"></script>
    <script src="{%static 'js/bootstrap.min.js' %}"></script>
    <script src="{%static 'js/owl.carousel.min.js' %}"></script>
    <script src="{%static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{%static 'js/ajax-form.js' %}"></script>
    <script src="{%static 'js/waypoints.min.js' %}"></script>
    <script src="{%static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{%static 'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{%static 'js/scrollIt.js' %}"></script>
    <script src="{%static 'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{%static 'js/wow.min.js' %}"></script>
    <script src="{%static 'js/nice-select.min.js' %}"></script>
    <script src="{%static 'js/jquery.slicknav.min.js' %}"></script>
    <script src="{%static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{%static 'js/plugins.js' %}"></script>
    <!-- <script src="js/gijgo.min.js"></script> -->
    <script src="{%static 'js/range.js'%}"></script>



    <!--contact js-->
    <script src="{%static 'js/contact.js' %}"></script>
    <script src="{%static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{%static 'js/jquery.form.js' %}"></script>
    <script src="{%static 'js/jquery.validate.min.js' %}"></script>
    <script src="{%static 'js/mail-script.js' %}"></script>


    <script src="{%static 'js/main.js' %}"></script>


	<script>
        $( function() {
            $( "#slider-range" ).slider({
                range: true,
                min: 0,
                max: 24600,
                values: [ 750, 24600 ],
                slide: function( event, ui ) {
                    $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] +"/ Year" );
                }
            });
            $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
                " - $" + $( "#slider-range" ).slider( "values", 1 ) + "/ Year");
        } );
        </script>
</body>

</html>

templates/home/home.html
{% extends 'base.html' %}

{% load bootstrap5form %}



{% block body %}
      
    <!-- slider_area_start -->
    <div class="slider_area">
        <div class="single_slider  d-flex align-items-center slider_bg_1">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-7 col-md-6">
                        <div class="slider_text">
                           
                            <h3 class="wow fadeInLeft" data-wow-duration="1s" data-wow-delay=".3s">Find your Dream Job</h3>
                            <p class="wow fadeInLeft" data-wow-duration="1s" data-wow-delay=".4s">We provide online instant cash loans with quick approval that suit your term length</p>
                            <div class="sldier_btn wow fadeInLeft" data-wow-duration="1s" data-wow-delay=".5s">
                                <a href="{%url 'jobs:job_list'%}" class="boxed-btn3">Choose Your Job</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="ilstration_img wow fadeInRight d-none d-lg-block text-right" data-wow-duration="1s" data-wow-delay=".2s">
            <img src="img/banner/illustration.png" alt="">
        </div>
    </div>
    <!-- slider_area_end -->

    <!-- catagory_area -->
 

    

    <!-- job_searcing_wrap  -->
    <div class="job_searcing_wrap overlay">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 offset-lg-1 col-md-6">
                    <div class="searching_text">
                        <h3>Looking for a Job?</h3>
                        <p>We provide online instant cash loans with quick approval </p>
                        <a href="{%url 'jobs:job_list'%}" class="boxed-btn3">Browse Job</a>
                    </div>
                </div>
                <div class="col-lg-5 offset-lg-1 col-md-6">
                    <div class="searching_text">
                        <h3>Looking for a Expert?</h3>
                        <p>We provide online instant cash loans with quick approval </p>
                        <a href="{%url 'jobs:add'%}" class="boxed-btn3">Post a Job</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_searcing_wrap end  -->

    <!-- testimonial_area  -->

    <!-- /testimonial_area  -->

{% endblock body %}

templates/job/job_list.html
{% extends 'base.html' %}
{% load bootstrap5form %}
{% block body %}


<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{jobs.count}}+ Jobs Available</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- job_listing_area_start  -->
<div class="job_listing_area plus_padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="job_filter white-bg">
                    <div class="form_inner white-bg">
                        <h3>Filter</h3>
                        <form method="get">
                            {{ filter.form|bootstrap5form }}                      
                            <input type="submit" value="search" class="boxed-btn3 w-100">
                        </form>
                    </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Job Listing</h4>
                                </div>
                                <div class="col-md-6">
                                    <div class="serch_cat d-flex justify-content-end">                                                                           
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="job_lists  mx-0">
                        <div class="row">

                            {% for jobs in jobs %}
                            <div class="col-lg-12 col-md-12  mx-auto">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb">
                                            <img src="img/svg_icon/1.svg" alt="">
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{%url 'jobs:job_detail' jobs.slug%}">
                                                <h4>{{jobs}}</h4>
                                            </a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i> {{jobs.job_type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                                            <a href="{%url 'jobs:job_detail' jobs.slug %}" class="boxed-btn3">Apply
                                                Now</a>
                                        </div>
                                        <div class="date">
                                            <p>Date line: {{jobs.Published_at}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>

                        {% if jobs.has_other_pages %}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                        {% if jobs.has_previous %}
                                        <li><a href="?page={{jobs.previous_page_number}}"> <i class="ti-angle-left"></i>
                                            </a></li>
                                        {% endif %}

                                        {% for i in jobs.paginator.page_range %}
                                        <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {% endfor %}

                                        {% if jobs.has_next %}
                                        <li><a href="?page={{jobs.next_page_number}}"> <i class="ti-angle-right"></i>
                                            </a>
                                        </li>
                                        {% endif %}

                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->
    {% endblock body %}